--- #YAML:1.0
name: Mail-TempAddress-Addresses-Purgeable
version: 0.12
license: perl
distribution_type: module
requires:
  Mail::TempAddress: '<=0.53'
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Mail::TempAddress::Addresses::Purgeable:
    file: lib/Mail/TempAddress/Addresses/Purgeable.pm
    version: 0.12
generated_by: Module::Build version 0.21
